# Generated by Django 3.1.7 on 2022-07-26 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientElectricBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_flat', models.PositiveSmallIntegerField(unique=True, verbose_name='Квартира №')),
                ('name_contact_person', models.CharField(max_length=50, verbose_name='Контактна особа')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('address_street', models.CharField(choices=[('Lazyrna_7', 'вул. Лазурна, буд. 7')], default='вул. Лазурна, буд. 7', max_length=30, verbose_name='Вулиця')),
                ('is_active', models.BooleanField(default=True, verbose_name='Нараховувати оплату')),
                ('month_start_pay_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], default='7', max_length=20, verbose_name='Місяць')),
                ('year_start_pay_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], default='2022', max_length=5, verbose_name='Рік')),
                ('note', models.TextField(blank=True, max_length=150, null=True, verbose_name='')),
                ('date_start_pay', models.DateField(blank=True, null=True)),
                ('square_meters', models.PositiveSmallIntegerField(verbose_name='Площадь, кв.м.')),
                ('square_meters_fractional', models.PositiveSmallIntegerField(default=0, verbose_name='Десяті')),
            ],
            options={
                'verbose_name': 'Квартира',
         # Generated by Django 3.1.7 on 2022-07-26 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientElectricBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_flat', models.PositiveSmallIntegerField(unique=True, verbose_name='Квартира №')),
                ('name_contact_person', models.CharField(max_length=50, verbose_name='Контактна особа')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('address_street', models.CharField(choices=[('Lazyrna_7', 'вул. Лазурна, буд. 7')], default='вул. Лазурна, буд. 7', max_length=30, verbose_name='Вулиця')),
                ('is_active', models.BooleanField(default=True, verbose_name='Нараховувати оплату')),
                ('month_start_pay_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], default='7', max_length=20, verbose_name='Місяць')),
                ('year_start_pay_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], default='2022', max_length=5, verbose_name='Рік')),
                ('note', models.TextField(blank=True, max_length=150, null=True, verbose_name='')),
                ('date_start_pay', models.DateField(blank=True, null=True)),
                ('square_meters', models.PositiveSmallIntegerField(verbose_name='Площадь, кв.м.')),
                ('square_meters_fractional', models.PositiveSmallIntegerField(default=0, verbose_name='Десяті')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартири',
                'db_table': 'numb_flat',
                'ordering': ('numb_flat',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_report', models.CharField(choices=[('debtor', 'Боржники')], default='Боржники', max_length=30, verbose_name='Тип звіту')),
                ('month_till_report', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], default='7', max_length=20, verbose_name='Місяць')),
                ('year_till_report', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], default='2022', max_length=5, verbose_name='Рік')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='TariffForBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_tariff_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], max_length=20, verbose_name='Від місяць')),
                ('year_start_tariff_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=5, verbose_name='рік')),
                ('month_end_tariff_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], max_length=20, verbose_name='До місяць')),
                ('year_end_tariff_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=5, verbose_name='рік')),
                ('sum_tariff_to_pay', models.PositiveSmallIntegerField(verbose_name='Сума тарифу, грн.')),
                ('sum_tariff_to_pay_cop', models.PositiveSmallIntegerField(verbose_name='Сума тарифу, коп.')),
                ('date_start_tariff', models.DateField(blank=True, null=True)),
                ('date_end_tariff', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'db_table': 'tariff',
                'ordering': ('-year_start_tariff_bill', '-month_start_tariff_bill'),
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_tariff_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], max_length=20, verbose_name='Від місяць')),
                ('year_start_tariff_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=5, verbose_name='рік')),
                ('month_end_tariff_bill', models.CharField(choices=[('1', 'Січень(01)'), ('2', 'Лютий(02)'), ('3', 'Березень(03)'), ('4', 'Квітень(04)'), ('5', 'Травень(05)'), ('6', 'Червень(06)'), ('7', 'Липень(07)'), ('8', 'Серпень(08)'), ('9', 'Вересень(09)'), ('10', 'Жовтень(10)'), ('11', 'Листопад(11)'), ('12', 'Грудень(12)')], max_length=20, verbose_name='До місяць')),
                ('year_end_tariff_bill', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=5, verbose_name='рік')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Процентов')),
                ('date_start_tariff', models.DateField(blank=True, null=True)),
                ('date_end_tariff', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electric_bill.clientelectricbill', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготи',
                'db_table': 'privilege',
                'ordering': ('-year_start_tariff_bill', '-month_start_tariff_bill'),
            },
        ),
        migrations.CreateModel(
            name='PayElectricBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_pay_bill', models.CharField(blank=True, max_length=20, null=True, verbose_name='Від місяць')),
                ('year_start_pay_bill', models.CharField(blank=True, max_length=5, null=True, verbose_name='рік')),
                ('month_end_pay_bill', models.CharField(blank=True, max_length=20, null=True, verbose_name='До місяць')),
                ('year_end_pay_bill', models.CharField(blank=True, max_length=5, null=True, verbose_name='рік')),
                ('date_pay', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 14, 47, 14, 962161), verbose_name='Дата оплати')),
                ('sum_to_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сума оплати, грн.')),
                ('col_month_to_pay', models.PositiveSmallIntegerField(verbose_name='Кількість місяців до сплати')),
                ('date_start_pay', models.DateField(blank=True, null=True)),
                ('date_end_pay', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electric_bill.clientelectricbill', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
                'db_table': 'pay_electric_bill',
                'ordering': ('date_pay',),
            },
        ),
    ]
